const server = require('./config/server')
require('./config/database')

//MÓDULOS EDUARDO
require('./api/rotas/unidade')(server)
require('./api/rotas/pedido')(server)
require('./api/rotas/fornecedor')(server)
require('./api/rotas/nota')(server)
require('./api/rotas/estoque')(server)
require('./api/rotas/produto')(server)
require('./api/rotas/usuario')(server)
require('./api/rotas/setor')(server)
require('./api/rotas/categoriaProd')(server)
//********************** */

require('./api/rotas/cadpais')(server)
require('./api/rotas/escolaridade')(server)
require('./api/rotas/categoria')(server)
require('./api/rotas/cidade')(server)
require('./api/rotas/dmed')(server)
require('./api/rotas/empresa')(server)
require('./api/rotas/descExames')(server)
require('./api/rotas/examemedico')(server)
require('./api/rotas/examepsicologico')(server)
require('./api/rotas/filaatendimento')(server)
require('./api/rotas/livrofinanceiro')(server)
require('./api/rotas/tipolog')(server)
require('./api/rotas/motivoreajuste')(server)
require('./api/rotas/notafiscal')(server)
require('./api/rotas/paciente')(server)
require('./api/rotas/cadpais')(server)
require('./api/rotas/protocolo')(server)
require('./api/rotas/reajustelivro')(server)
require('./api/rotas/renach')(server)
require('./api/rotas/restricoes')(server)
require('./api/rotas/resultexame')(server)
require('./api/rotas/tipoDoc')(server)
require('./api/rotas/usuarios')(server)
require('./api/rotas/dadosExameMedico')(server)
require('./api/rotas/tabelasTestes')(server)
require('./api/rotas/referencias')(server)
require('./api/rotas/testesPsico')(server)
require('./api/rotas/construtos')(server)
require('./api/rotas/sinteses')(server)
require('./api/rotas/parametrosLaudo')(server)
require('./api/rotas/dashboard')(server)
require('./api/rotas/bakupagend')(server)
require('./api/rotas/financeiro')(server)
require('./api/rotas/perfil')(server)
require('./api/rotas/categoriafinanc')(server)
require('./api/rotas/contaspagar')(server)
require('./api/rotas/contasreceber')(server)
require('./api/rotas/despesasfixas')(server)
require('./api/rotas/receitasfixas')(server)



require('./config/routes')(server)

